ComicShopApplication/Shop.Web/Controllers/OrderController.cs
using ClosedXML.Excel;
using GemBox.Document;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Shop.Domain.DomainModels;
using System.Text;

namespace Shop.Web.Controllers
{
    public class OrderController : Controller
    {

        public OrderController()
        {
            ComponentInfo.SetLicense("FREE-LIMITED-KEY");
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Index()
        {
            HttpClient client = new HttpClient();

            string URL = "https://localhost:7060/api/Admin/GetOrders";

            HttpResponseMessage response = client.GetAsync(URL).Result;

            var result = response.Content.ReadAsAsync<List<Order>>().Result;

            return View(result);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Details(Guid id)
        {
            HttpClient client = new HttpClient();

            string URL = "https://localhost:7060/api/Admin/GetDetailsForOrder";

            var model = new
            {
                Id = id
            };


            HttpContent content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");


            HttpResponseMessage response = client.PostAsync(URL, content).Result;

            var result = response.Content.ReadAsAsync<Order>().Result;

            return View(result);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult CreateInvoice(Guid id)
        {
            HttpClient client = new HttpClient();

            string URL = "https://localhost:7060/api/Admin/GetDetailsForOrder";

            var model = new
            {
                Id = id
            };


            HttpContent content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");


            HttpResponseMessage response = client.PostAsync(URL, content).Result;

            var result = response.Content.ReadAsAsync<Order>().Result;

            var templatePath = Path.Combine(Directory.GetCurrentDirectory(), "Invoice.docx");

            var document = DocumentModel.Load(templatePath);

            document.Content.Replace("{{OrderNumber}}", result.Id.ToString());
            document.Content.Replace("{{CostumerEmail}}", result.User.Email);
            document.Content.Replace("{{CostumerInfo}}", (result.User.FirstName + " " + result.User.LastName));

            StringBuilder sb = new StringBuilder();

            var total = 0.0;

            foreach (var item in result.ComicInOrders)
            {
                total += item.Quantity * item.Comic.ComicPrice;
                sb.AppendLine(item.Comic.ComicName + " with quantity of: " + item.Quantity + " and price of: " + item.Comic.ComicPrice + " ДЕН.");
            }

            document.Content.Replace("{{AllComics}}", sb.ToString());
            document.Content.Replace("{{TotalPrice}}", total.ToString() + " ДЕН.");

            var stream = new MemoryStream();

            document.Save(stream, new PdfSaveOptions());


            return File(stream.ToArray(), new PdfSaveOptions().ContentType, "ExportInvoice.pdf");
        }

        [Authorize(Roles = "Administrator")]
        public FileContentResult ExportAllOrders(Guid id)
        {
            HttpClient client = new HttpClient();

            string URL = "https://localhost:7060/api/Admin/GetOrders";

            HttpResponseMessage response = client.GetAsync(URL).Result;

            var result = response.Content.ReadAsAsync<List<Order>>().Result;

            string fileName = "Orders.xlsx";
            string contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

            using (var workBook = new XLWorkbook())
            {
                IXLWorksheet worksheet = workBook.Worksheets.Add("All Orders");

                worksheet.Cell(1, 1).Value = "Order Id";
                worksheet.Cell(1, 2).Value = "Costumer Name";
                worksheet.Cell(1, 3).Value = "Costumer Last Name";
                worksheet.Cell(1, 4).Value = "Costumer Email";

                for (int i = 1; i <= result.Count(); i++)
                {
                    var item = result[i - 1];

                    worksheet.Cell(i + 1, 1).Value = item.Id.ToString();
                    worksheet.Cell(i + 1, 2).Value = item.User.FirstName;
                    worksheet.Cell(i + 1, 3).Value = item.User.LastName;
                    worksheet.Cell(i + 1, 4).Value = item.User.Email;

                    for (int p = 1; p <= item.ComicInOrders.Count(); p++)
                    {
                        worksheet.Cell(1, p + 4).Value = "Comic-" + (p);
                        worksheet.Cell(i + 1, p + 4).Value = item.ComicInOrders.ElementAt(p - 1).Comic.ComicName;
                    }

                }

                using (var stream = new MemoryStream())
                {
                    workBook.SaveAs(stream);

                    var content = stream.ToArray();

                    return File(content, contentType, fileName);
                }
            }

        }
    }
}

ComicShopApplication/Shop.Web/Controllers/UserController.cs
using ExcelDataReader;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Shop.Domain.DTO;
using System.Text;

namespace Shop.Web.Controllers
{
    public class UserController : Controller
    {
        [Authorize(Roles = "Administrator")]
        [HttpGet("[action]")]
        public IActionResult ImportUsers()
        {
            return View();
        }

        [HttpPost("[action]")]
        [Authorize(Roles = "Administrator")]
        public IActionResult ImportUsers(IFormFile file)
        {

            //make a copy
            string pathToUpload = $"{Directory.GetCurrentDirectory()}\\files\\{file.FileName}";


            using (FileStream fileStream = System.IO.File.Create(pathToUpload))
            {
                file.CopyTo(fileStream);

                fileStream.Flush();
            }

            //read data from uploaded file

            List<UserRegistrationDto> users = getUsersFromExcelFile(file.FileName);

            HttpClient client = new HttpClient();

            string URL = "https://localhost:7060/api/Admin/ImportAllUsers";

            HttpContent content = new StringContent(JsonConvert.SerializeObject(users), Encoding.UTF8, "application/json");

            HttpResponseMessage response = client.PostAsync(URL, content).Result;

            var result = response.Content.ReadAsAsync<bool>().Result;

            return RedirectToAction("Index", "Comics");
        }

        private List<UserRegistrationDto> getUsersFromExcelFile(string fileName)
        {

            string pathToFile = $"{Directory.GetCurrentDirectory()}\\files\\{fileName}";

            System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);

            List<UserRegistrationDto> userList = new List<UserRegistrationDto>();

            using (var stream = System.IO.File.Open(pathToFile, FileMode.Open, FileAccess.Read))
            {
                using (var reader = ExcelReaderFactory.CreateReader(stream))
                {
                    while (reader.Read())
                    {
                        userList.Add(new UserRegistrationDto
                        {
                            FirstName = reader.GetValue(0).ToString(),
                            LastName = reader.GetValue(1).ToString(),
                            Email = reader.GetValue(2).ToString(),
                            Password = reader.GetValue(3).ToString(),
                            ConfirmPassword = reader.GetValue(4).ToString(),
                            PhoneNumber = reader.GetValue(5).ToString()
                        });
                    }
                }
            }

            return userList;

        }
    }
}

ComicShopApplication/Shop.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Shop.Domain.Identity.ShopApplicationUser> SignInManager
@inject UserManager<Shop.Domain.Identity.ShopApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Comic Shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EShopWeb.styles.css" asp-append-version="true" />
</head>
<body style="background-color: #e5e5f7; opacity: 1; background-image:  linear-gradient(135deg, #C7C0F0 25%, transparent 25%), linear-gradient(225deg, #C7C0F0 25%, transparent 25%), linear-gradient(45deg, #C7C0F0 25%, transparent 25%), linear-gradient(315deg, #C7C0F0 25%, #e5e5f7 25%); background-position:  10px 0, 10px 0, 0 0, 0 0; background-size: 10px 10px; background-repeat: repeat;">
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary mb-3" style="background-color: #FFF7ED">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Comic Shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="About">About Us</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class=nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="true" asp-area="" asp-controller="Comics" asp-action="Index">Comics</a>
                            <ul class="dropdown-menu">
                                <li><a class="nav-link" asp-area="" asp-controller="Comics" asp-action="Index">All Comics</a></li>
                                <li><div class="dropdown-divider"></div></li>
                                <li><a class="dropdown-item" href="@Url.Action("Index", "Comics", new { genre = "Action" })">Action</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("Index", "Comics", new { genre = "Adventure" })">Adventure</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("Index", "Comics", new { genre = "Fantasy" })">Fantasy</a></li>
                                  <li><a class="dropdown-item" href="@Url.Action("Index", "Comics", new { genre = "Science Fiction" })">Science Fiction</a></li>
                                  <li><a class="dropdown-item" href="@Url.Action("Index", "Comics", new { genre = "Horror" })">Horror</a></li>
                                  <li><a class="dropdown-item" href="@Url.Action("Index", "Comics", new { genre = "Other" })">Other</a></li>
                              </ul>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                 <a class="nav-link active" asp-area="" asp-controller="ShoppingCart" asp-action="Index">Shopping Cart</a>
                            </li>
                        }
                        @if (User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                 <a class="nav-link active" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                            </li>
                            <li class="nav-item">
                                 <a class="nav-link active" asp-area="" asp-controller="User" asp-action="ImportUsers">Import Users</a>
                            </li>
                            <li class="nav-item">
                                 <a class="nav-link active" asp-area="" asp-controller="Account" asp-action="AddUserToRole">Add Role to Users</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container rounded-3" style="background-color: #FFF7ED">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <div class="container-fluid" style="background-color: #FFF7ED">
        <div class="container">
          <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <p class="col-md-4 mb-0 text-muted">© 2023 Comic Shop</p>

            <ul class="nav col-md-4 justify-content-end">
              <li class="nav-item"><a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Comic Shop</a></li>
              <li class="nav-item"><a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="About">About Us</a></li>
            </ul>
          </footer>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>